<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#计算日内动量因子值示例" data-toc-modified-id="计算日内动量因子值示例-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>计算日内动量因子值示例</a></span><ul class="toc-item"><li><span><a href="#计算个股日内动量值" data-toc-modified-id="计算个股日内动量值-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>计算个股日内动量值</a></span></li><li><span><a href="#计算各个日内动量的IC均值及协方差" data-toc-modified-id="计算各个日内动量的IC均值及协方差-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>计算各个日内动量的IC均值及协方差</a></span><ul class="toc-item"><li><span><a href="#构建日内动量因子值数据结构factor_data" data-toc-modified-id="构建日内动量因子值数据结构factor_data-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>构建日内动量因子值数据结构factor_data</a></span></li><li><span><a href="#构建股票价格数据结构prices" data-toc-modified-id="构建股票价格数据结构prices-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>构建股票价格数据结构prices</a></span></li><li><span><a href="#清洗数据，得到日内各个时点清洗后的动量数据" data-toc-modified-id="清洗数据，得到日内各个时点清洗后的动量数据-1.2.3"><span class="toc-item-num">1.2.3&nbsp;&nbsp;</span>清洗数据，得到日内各个时点清洗后的动量数据</a></span></li><li><span><a href="#计算日内各个时点动量的IC值" data-toc-modified-id="计算日内各个时点动量的IC值-1.2.4"><span class="toc-item-num">1.2.4&nbsp;&nbsp;</span>计算日内各个时点动量的IC值</a></span></li><li><span><a href="#计算最优权重向量" data-toc-modified-id="计算最优权重向量-1.2.5"><span class="toc-item-num">1.2.5&nbsp;&nbsp;</span>计算最优权重向量</a></span><ul class="toc-item"><li><span><a href="#计算IC的均值向量$\overline{IC}$和协方差矩阵$\Sigma$" data-toc-modified-id="计算IC的均值向量$\overline{IC}$和协方差矩阵$\Sigma$-1.2.5.1"><span class="toc-item-num">1.2.5.1&nbsp;&nbsp;</span>计算IC的均值向量$\overline{IC}$和协方差矩阵$\Sigma$</a></span></li><li><span><a href="#计算协方差矩阵的逆矩阵" data-toc-modified-id="计算协方差矩阵的逆矩阵-1.2.5.2"><span class="toc-item-num">1.2.5.2&nbsp;&nbsp;</span>计算协方差矩阵的逆矩阵</a></span></li><li><span><a href="#计算最优权重向量" data-toc-modified-id="计算最优权重向量-1.2.5.3"><span class="toc-item-num">1.2.5.3&nbsp;&nbsp;</span>计算最优权重向量</a></span></li></ul></li><li><span><a href="#保存最优权重向量" data-toc-modified-id="保存最优权重向量-1.2.6"><span class="toc-item-num">1.2.6&nbsp;&nbsp;</span>保存最优权重向量</a></span></li></ul></li></ul></li></ul></div>

In [6]:
%pylab inline --no-import-all
import pandas as pd
from pandas import DataFrame
from pandas import Series
import numpy as np
import alphalens
import datetime
import os
import math
from jaqs.data.dataapi import DataApi
import tushare as ts
api = DataApi(addr='tcp://data.tushare.org:8910')
api.login("13811931480", "eyJhbGciOiJIUzI1NiJ9.eyJjcmVhdGVfdGltZSI6IjE1MTI4Nzk0NTI2MjkiLCJpc3MiOiJhdXRoMCIsImlkIjoiMTM4MTE5MzE0ODAifQ.I0SXsA1bK--fbGu0B5Is2xdKOjALAeWBJRX6GdVmUL8")

Populating the interactive namespace from numpy and matplotlib


('username: 13811931480', '0,')

# 计算日内动量因子值示例

## 计算个股日内动量值

In [36]:
# 取得过去90天的交易日序列，降序排列
end_date = datetime.datetime(2017, 12, 27)
start_date = end_date - datetime.timedelta(days=90)
df_trading_day, msg = api.query(
                                view="jz.secTradeCal",
                                fields="date,istradeday,isweekday,isholiday",
                                filter="start_date=%s&end_date=%s" % (start_date.strftime('%Y%m%d'), end_date.strftime('%Y%m%d')),
                                data_format='pandas')
df_trading_day.sort_values(by='trade_date', ascending=False, inplace=True)

# 遍历交易日序列，取得过去21个交易日的1分钟行情中的5个时点的价格
mkt_data = DataFrame()
mkt_data_header = ['date', 'p0930', 'p1030', 'p1130', 'p1400', 'p1500']
k = 0
for _, trading_day_info in df_trading_day.iterrows():
    df_1m_mkt, msg = api.bar(symbol = '600000.SH',
                             trade_date = trading_day_info.trade_date,
                             freq = '1M',
                             start_time = 92500,
                             end_time = 150000,
                             fields='')
    if len(df_1m_mkt) > 0:
        strdate = str(df_1m_mkt.iloc[0].date)
        p0930 = df_1m_mkt[df_1m_mkt.time==93100].iloc[0].open
        p1030 = df_1m_mkt[df_1m_mkt.time==103000].iloc[0].close
        p1130 = df_1m_mkt[df_1m_mkt.time==113000].iloc[0].close
        p1400 = df_1m_mkt[df_1m_mkt.time==140000].iloc[0].close
        p1500 = df_1m_mkt[df_1m_mkt.time==150000].iloc[0].close
        s = Series([strdate, p0930, p1030, p1130, p1400, p1500], index=mkt_data_header)
        mkt_data = mkt_data.append(s,ignore_index=True)
        k += 1
    if k > 20:
        break
mkt_data.sort_values(by='date',inplace=True)
mkt_data.reset_index(drop=True, inplace=True)
print(mkt_data[mkt_data_header])

# 计算传统的动量因子值，=过去20日涨跌幅
m_normal = math.log(mkt_data.iloc[-1].p1500 / mkt_data.iloc[0].p1500)
print('normal momentum value = %.6f' % m_normal)

# 遍历上述取得的行情数据，计算每日的日内收益值
intra_day_ret = DataFrame()
ret_header = ['date', 'r0', 'r1', 'r2', 'r3', 'r4']
for k in range(1,21):
    strdate = mkt_data.iloc[k].date
    r0 = math.log(mkt_data.iloc[k].p0930 / mkt_data.iloc[k-1].p1500)
    r1 = math.log(mkt_data.iloc[k].p1030 / mkt_data.iloc[k].p0930)
    r2 = math.log(mkt_data.iloc[k].p1130 / mkt_data.iloc[k].p1030)
    r3 = math.log(mkt_data.iloc[k].p1400 / mkt_data.iloc[k].p1130)
    r4 = math.log(mkt_data.iloc[k].p1500 / mkt_data.iloc[k].p1400)
    s = Series([strdate, r0, r1, r2, r3, r4], index=ret_header)
    intra_day_ret = intra_day_ret.append(s, ignore_index=True)
intra_day_ret = intra_day_ret.set_index('date')

# 个股的日内各时点的动量因子值等于过去20个交易日各r_i累加
intra_day_momentum = intra_day_ret.sum()
intra_day_momentum.index=['m0','m1','m2','m3','m4']
intra_day_momentum['m_normal'] = m_normal
intra_day_momentum

        date  p0930  p1030  p1130  p1400  p1500
0   20171129  12.95  12.87  12.89  12.92  12.90
1   20171130  12.91  12.85  12.88  12.90  12.91
2   20171201  12.93  12.84  12.81  12.87  12.92
3   20171204  12.87  12.87  12.86  12.86  12.93
4   20171205  12.92  13.04  13.10  13.14  13.17
5   20171206  13.12  13.00  13.03  13.01  12.96
6   20171207  12.95  12.98  12.94  12.98  12.96
7   20171208  12.98  12.94  12.94  12.91  12.92
8   20171211  12.92  12.89  12.94  13.02  12.97
9   20171212  12.97  12.92  12.83  12.82  12.74
10  20171213  12.80  12.78  12.70  12.78  12.75
11  20171214  12.79  12.74  12.69  12.67  12.69
12  20171215  12.69  12.67  12.68  12.67  12.62
13  20171218  12.71  12.66  12.62  12.65  12.65
14  20171219  12.65  12.69  12.72  12.73  12.75
15  20171220  12.76  12.67  12.66  12.63  12.72
16  20171221  12.67  12.68  12.76  12.73  12.70
17  20171222  12.68  12.66  12.67  12.64  12.62
18  20171225  12.61  12.64  12.61  12.61  12.60
19  20171226  12.57  12.63  12.61  12.62

m0          0.002459
m1         -0.028701
m2         -0.009577
m3          0.013068
m4          0.000806
m_normal   -0.021944
dtype: float64

## 计算各个日内动量的IC均值及协方差

In [4]:
class Cache(object):

    def __init__(self, maxsize=100):
        self.cache = {}
        self.order = []     # least recently used first
        self.maxsize = maxsize

    def get(self, key):
        try:
            item = self.cache[key]  # KeyErroe if not present
            self.order.remove(key)
            self.order.append(key)
        except KeyError:
            item = None
        return item

    def set(self, key, value):
        if key in self.cache:
            self.order.remove(key)
        elif len(self.cache) >= self.maxsize:
            # discard least recently used item
            del self.cache[self.order.pop(0)]
        self.cache[key] = value
        self.order.append(key)

    def size(self):
        return len(self.cache)

In [11]:
utils_trading_days = pd.Series()
ts_conn = ts.get_apis()
df_SZZS = ts.bar(code='000001', conn=ts_conn, asset='INDEX')
ts.close_apis(ts_conn)
utils_trading_days = pd.Series(df_SZZS.index).sort_values()

def get_trading_days(start=None, end=None, ndays=None, ascending=True):
    """
    取得交易日列表，分三种方式取得
    （1）指定开始、结束日期，即start和end不为None，此时忽略参数ndays
    （2）指定开始日期和天数，即start和ndays不为None，而end为None
    （3）指定结束日期和天数，即end和ndays为None，而start为None
    --------
    :param start: datetime-like or str
        开始日期，格式：YYYY-MM-DD
    :param end: datetime-like or str
        结束日期，格式：YYYY-MM-DD
    :param ndays: int
        交易日天数
    :param ascending: bool，默认True
        是否升序排列
    :return:
    --------
        Series of pandas.Timestamp，交易日列表，默认按交易日升序排列
    """
    if start is not None and end is not None:
        trading_days = utils_trading_days[(utils_trading_days >= start) & (utils_trading_days <= end)]
    elif start is not None and ndays is not None:
        trading_days = utils_trading_days[utils_trading_days >= start].iloc[:ndays]
    elif end is not None and ndays is not None:
        trading_days = utils_trading_days[utils_trading_days <= end].iloc[-ndays:]
    elif start is not None:
        trading_days = utils_trading_days[utils_trading_days >= start]
    elif end is not None:
        trading_days = utils_trading_days[utils_trading_days <= end]
    elif ndays is not None:
        trading_days = utils_trading_days[-ndays:]
    else:
        trading_days = utils_trading_days
    trading_days = trading_days.reset_index(drop=True)
    if not ascending:
        trading_days = trading_days.sort_values(ascending=False)
    return trading_days
# ------------------------------------
def to_date(date_like):
    if isinstance(date_like, datetime.datetime) or isinstance(date_like, datetime.date):
        return date_like
    else:
        return datetime.datetime.strptime(date_like.replace('-', ''), '%Y%m%d')
# -------------------------------------
def is_month_end(trading_day):
    """
    是否时月末的交易日
    :param trading_day: datetime-like, str
    :return: bool
    """
    trading_day = to_date(trading_day)
    trading_days = get_trading_days(start=trading_day, ndays=2)
    if trading_day != trading_days[0]:
        return False
    else:
        if trading_day.month == trading_days[1].month:
            return False
        else:
            return True
# ------------------------------------
MKT_DAILY_FQ_HEADER = ['code', 'date', 'open', 'high', 'low', 'close', 'vol', 
                       'amount', 'turnover1', 'turnover2', 'factor']
DataCache = Cache(3000)
def is_normal_traded(code, trading_day):
    """
    个股在指定交易日是否正常交易
    """
    daily_mkt_path = '/Volumes/DB/FactorDB/ElementaryFactor/mkt_daily_FQ/%s.csv' % code
    if not os.path.isfile(daily_mkt_path):
        return False
    key = '%s_daily_mkt_%s' % (code, to_date(trading_day).strftime('%Y%m%d'))
    df_daily_mkt = DataCache.get(key)
    if df_daily_mkt is None:
        df_daily_mkt = pd.read_csv(daily_mkt_path, 
                                   names=MKT_DAILY_FQ_HEADER, 
                                   parse_dates=[1],
                                   header=0)
        DataCache.set(key, df_daily_mkt)
    
    if len(df_daily_mkt[df_daily_mkt.date==to_date(trading_day)]) > 0:
        return True
    else:
        return False

### 构建日内动量因子值数据结构factor_data

In [13]:
start_date = '2012-12-31'
end_date = '2017-11-30'
# 取得开始、结束日期之间的交易日序列
trading_days = get_trading_days(start_date, end_date)
# 遍历交易日期，如果是月末，则读取日内动量因子载荷
factor_data = DataFrame()
for trading_day in trading_days:
    if is_month_end(trading_day):
        factor_data_path = '/Volumes/DB/FactorDB/Momentum/IntradayMomentum/IntradayMomentum_%s.csv' % trading_day.strftime('%Y%m%d')
        factor_data = factor_data.append(pd.read_csv(factor_data_path,
                                                     parse_dates=[0],
                                                     names=['date', 'asset', 'm0', 'm1', 'm2', 'm3', 'm4', 'm_normal'],
                                                     header=0),
                                         ignore_index=True)
# 遍历factor_data，剔除个股在调仓日期没有正常交易（如停牌）的个股
ind_to_be_deleted = []
for ind, factor_info in factor_data.iterrows():
    if not is_normal_traded(factor_info.asset, factor_info.date):
        ind_to_be_deleted.append(ind)
factor_data = factor_data.drop(ind_to_be_deleted, axis=0)
# 保存factor_data数据
factor_data_path = '/Volumes/DB/FactorDB/Momentum/IntradayMomentum/IntradayMomentum_Factor_Data.csv'
factor_data.to_csv(factor_data_path, index=False, columns=['date', 'asset', 'm0', 'm1', 'm2', 'm3', 'm4', 'm_normal'])
# 对factor_data进行层次化索引, level0=date, level1=asset
factor_data = factor_data.set_index(['date', 'asset'])
factor_data.head()

m0        m1        m2        m3        m4  \
date       asset                                                        
2013-01-04 SZ000009 -0.007545  0.113670  0.019884  0.031413  0.002426   
           SZ000001 -0.018404  0.139996  0.063876 -0.005832  0.063684   
           SZ000027  0.012383 -0.001074  0.009271  0.065219 -0.021928   
           SZ000039  0.005219  0.141893  0.015784  0.046461  0.021843   
           SZ000046 -0.046495  0.228457  0.048684  0.046712  0.076675   

                     m_normal  
date       asset               
2013-01-04 SZ000009  0.159848  
           SZ000001  0.243321  
           SZ000027  0.063870  
           SZ000039  0.231198  
           SZ000046  0.354032

In [40]:
a = DataFrame(factor_data['m0'], columns=['factor'])
a.head()

factor
date       asset             
2013-01-04 SZ000009 -0.007545
           SZ000001 -0.018404
           SZ000027  0.012383
           SZ000039  0.005219
           SZ000046 -0.046495

### 构建股票价格数据结构prices

In [33]:
dates = list(factor_data.index.levels[0])
dates.append(pd.Timestamp('2017-12-29'))
codes = list(factor_data.index.levels[1])
prices = DataFrame(np.zeros((len(dates), len(codes))), columns=codes, index=dates)
prices.index.name = 'Date'
mkt_header = ['code', 'date', 'open', 'high', 'low', 'close', 'vol', 'amount', 'turnover1', 'turnover2', 'factor']
for date in dates:
    for code in codes:
        df_mkt_data = pd.read_csv('/Volumes/DB/FactorDB/ElementaryFactor/mkt_daily_FQ/%s.csv' % code,
                                  parse_dates=[1],names=mkt_header,header=0)
        if len(df_mkt_data[df_mkt_data.date == date]) == 0:
            if len(df_mkt_data[df_mkt_data.date<=date]) == 0:
                prices.loc[date,code] = 0.0
            else:
                prices.loc[date,code] = df_mkt_data[df_mkt_data.date<=date].iloc[-1].open
        else:
            prices.loc[date,code] = df_mkt_data[df_mkt_data.date==date].iloc[-1].open
prices_data_path = '/Volumes/DB/FactorDB/Momentum/IntradayMomentum/IntradayMomentum_Prices.csv'
prices.to_csv(prices_data_path)
prices.head()

SH600000  SH600004  SH600006  SH600007  SH600008  SH600009  \
Date                                                                     
2013-01-04   69.7434   10.5061   10.4215   18.1558   14.8277   34.2254   
2013-02-01   78.7894   11.1849   11.0468   17.7782   15.3682   36.2210   
2013-03-01   76.4416   11.0226   10.9078   18.3603   18.7458   36.1117   
2013-04-01   69.4672   10.2258    9.9351   17.8884   26.0077   36.4124   
2013-05-02   67.4647   10.1077   10.1088   16.4409   24.4878   34.0887   

            SH600010  SH600011  SH600012  SH600015    ...     SZ300683  \
Date                                                  ...                
2013-01-04   16.3300   25.2001    7.2299   19.7041    ...          0.0   
2013-02-01   15.8280   23.9224    7.3902   21.4903    ...          0.0   
2013-03-01   14.7944   23.4610    7.3368   20.9135    ...          0.0   
2013-04-01   14.7649   24.2418    7.0341   19.2948    ...          0.0   
2013-05-02   13.8790   22.6091    7.0341   19.3506    ...          0.0   

            SZ300685  SZ300686  SZ300688  SZ300689  SZ300690  SZ300691  \
Date                                                                     
2013-01-04       0.0       0.0       0.0       0.0       0.0       0.0   
2013-02-01       0.0       0.0       0.0       0.0       0.0       0.0   
2013-03-01       0.0       0.0       0.0       0.0       0.0       0.0   
2013-04-01       0.0       0.0       0.0       0.0       0.0       0.0   
2013-05-02       0.0       0.0       0.0       0.0       0.0       0.0   

            SZ300692  SZ300696  SZ300698  
Date                                      
2013-01-04       0.0       0.0       0.0  
2013-02-01       0.0       0.0       0.0  
2013-03-01       0.0       0.0       0.0  
2013-04-01       0.0       0.0       0.0  
2013-05-02       0.0       0.0       0.0  

[5 rows x 3340 columns]

### 清洗数据，得到日内各个时点清洗后的动量数据

In [87]:
# 清洗m0动量数据
factor_data_m0 = factor_data['m0']
factor_data_m0.rename(columns={'m0': 'factor'}, inplace=True)
m0_factor = alphalens.utils.get_clean_factor_and_forward_returns(factor_data_m0,
                                                                 prices,
                                                                 quantiles=5,
                                                                 periods=(1,))
# 清洗m1动量数据
factor_data_m1 = factor_data['m1']
factor_data_m1.rename(columns={'m1': 'factor'}, inplace=True)
m1_factor = alphalens.utils.get_clean_factor_and_forward_returns(factor_data_m1,
                                                                 prices,
                                                                 quantiles=5,
                                                                 periods=(1,))
# 清洗m2动量数据
factor_data_m2 = factor_data['m2']
factor_data_m2.rename(columns={'m2': 'factor'}, inplace=True)
m2_factor = alphalens.utils.get_clean_factor_and_forward_returns(factor_data_m2,
                                                                 prices,
                                                                 quantiles=5,
                                                                 periods=(1,))
# 清洗m3动量数据
factor_data_m3 = factor_data['m3']
factor_data_m3.rename(columns={'m3': 'factor'}, inplace=True)
m3_factor = alphalens.utils.get_clean_factor_and_forward_returns(factor_data_m3,
                                                                 prices,
                                                                 quantiles=5,
                                                                 periods=(1,))
# 清洗m4动量数据
factor_data_m4 = factor_data['m4']
factor_data_m4.rename(columns={'m4': 'factor'}, inplace=True)
m4_factor = alphalens.utils.get_clean_factor_and_forward_returns(factor_data_m4,
                                                                 prices,
                                                                 quantiles=5,
                                                                 periods=(1,))
# 清洗m_normal动量数据
factor_data_normal = factor_data['m_normal']
factor_data_normal.rename(columns={'m_normal': 'factor'}, inplace=True)
normal_factor = alphalens.utils.get_clean_factor_and_forward_returns(factor_data_normal,
                                                                     prices,
                                                                     quantiles=5,
                                                                     periods=(1,))

Dropped 0.0% entries from factor data (0.0% after in forward returns computation and 0.0% in binning phase). Set max_loss=0 to see potentially suppressed Exceptions.
Dropped 0.0% entries from factor data (0.0% after in forward returns computation and 0.0% in binning phase). Set max_loss=0 to see potentially suppressed Exceptions.
Dropped 0.0% entries from factor data (0.0% after in forward returns computation and 0.0% in binning phase). Set max_loss=0 to see potentially suppressed Exceptions.
Dropped 0.0% entries from factor data (0.0% after in forward returns computation and 0.0% in binning phase). Set max_loss=0 to see potentially suppressed Exceptions.
Dropped 0.0% entries from factor data (0.0% after in forward returns computation and 0.0% in binning phase). Set max_loss=0 to see potentially suppressed Exceptions.
Dropped 0.0% entries from factor data (0.0% after in forward returns computation and 0.0% in binning phase). Set max_loss=0 to see potentially suppressed Exceptions.


### 计算日内各个时点动量的IC值

In [88]:
ic_m0 = alphalens.performance.factor_information_coefficient(m0_factor)
ic_m1 = alphalens.performance.factor_information_coefficient(m1_factor)
ic_m2 = alphalens.performance.factor_information_coefficient(m2_factor)
ic_m3 = alphalens.performance.factor_information_coefficient(m3_factor)
ic_m4 = alphalens.performance.factor_information_coefficient(m4_factor)
ic_normal = alphalens.performance.factor_information_coefficient(normal_factor)

In [94]:
alphalens.plotting.plot_information_table(ic_m4)

Information Analysis


1
IC Mean          -0.019
IC Std.           0.093
Risk-Adjusted IC -0.211
t-stat(IC)       -1.631
p-value(IC)       0.108
IC Skew          -0.059
IC Kurtosis       0.616

### 计算最优权重向量
最优权重向量：$v^\ast = (s\Sigma^{-1}\cdot\overline{IC})^{\prime}$

#### 计算IC的均值向量$\overline{IC}$和协方差矩阵$\Sigma$
$\overline{IC}=(\overline{IC}_{m0},\overline{IC}_{m1},\overline{IC}_{m2},\overline{IC}_{m3},\overline{IC}_{m4})^{\prime}$

In [66]:
arr_ic0 = np.array(ic_m0)
arr_ic1 = np.array(ic_m1)
arr_ic2 = np.array(ic_m2)
arr_ic3 = np.array(ic_m3)
arr_ic4 = np.array(ic_m4)
arr_ic = np.column_stack((arr_ic0, arr_ic1, arr_ic2, arr_ic3, arr_ic4))
ic_cov_mat = np.cov(arr_ic, rowvar=False)
ic_cov_mat

array([[ 0.00655074, -0.00092362,  0.00035252,  0.00055861,  0.00323587],
       [-0.00092362,  0.01645347,  0.00411439,  0.00537996,  0.00135729],
       [ 0.00035252,  0.00411439,  0.00727354,  0.00166555, -0.00139555],
       [ 0.00055861,  0.00537996,  0.00166555,  0.00673081,  0.00018912],
       [ 0.00323587,  0.00135729, -0.00139555,  0.00018912,  0.00857231]])

#### 计算协方差矩阵的逆矩阵

In [67]:
ic_cov_mat_inv = np.linalg.inv(ic_cov_mat)
ic_cov_mat_inv

array([[209.77883748,  42.69633363, -43.23966603, -38.2488158 ,
        -92.1430223 ],
       [ 42.69633363, 102.70908405, -51.22026678, -71.86513247,
        -39.13242449],
       [-43.23966603, -51.22026678, 179.14187212,  -1.30666539,
         53.62467815],
       [-38.2488158 , -71.86513247,  -1.30666539, 208.92035741,
         20.99494328],
       [-92.1430223 , -39.13242449,  53.62467815,  20.99494328,
        165.89960614]])

In [68]:
ic_mean = np.mean(arr_ic, axis=0)
ic_mean.reshape((len(ic_mean), 1))

array([[ 0.0072798 ],
       [-0.012639  ],
       [-0.03698413],
       [-0.04875116],
       [-0.01949635]])

#### 计算最优权重向量

In [111]:
weight = np.dot(ic_cov_mat_inv, ic_mean)
print(weight)
s = np.sum(weight)
norm_weight = weight/s
norm_weight = norm_weight.reshape((1,len(norm_weight)))
norm_weight

[ 6.24781685  5.17346571 -7.2745935  -9.91624863 -6.41741437]


array([[-0.51266351, -0.42450782,  0.59691549,  0.81367603,  0.52657981]])

In [112]:
np.dot(weight, ic_mean)/np.sqrt(np.dot(np.dot(weight,ic_cov_mat),weight.T))

0.9261126760408023

### 保存最优权重向量

In [134]:
df_weight = DataFrame(np.around(norm_weight, decimals=4), columns=['w0', 'w1', 'w2', 'w3', 'w4'])
df_weight['date'] = '2018-01-02'
# df_weight
df_weight.to_csv('/Volumes/DB/FactorDB/Momentum/IntradayMomentum/optimal_weight.csv', index=False, 
                 columns=['date', 'w0', 'w1', 'w2', 'w3', 'w4'])